// ignore_for_file: prefer_const_constructors

import 'package:widgetbook_app/widgetbook.dart';

class CustomAvatarWidgetCase extends WidgetbookScrollableUseCase {
  CustomAvatarWidgetCase({super.name = 'Custom'})
      : super(
          builder: (context) => SectionH1Widgetbook(
            title: 'Custom Avatar',
            children: [
              SectionH2Widgetbook(
                title: 'Subtle',
                children: [
                  WrapLayout(
                    gap: 20,
                    children: [
                      AppAvatar(
                        style: WidgetStyle.subtle,
                        size: WidgetSize.xs,
                        title: 'Nonthawit Doungsodsri Text',
                        color: AppColor.blue.c500,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(10000.00),
                      ),
                      AppAvatar(
                        style: WidgetStyle.subtle,
                        size: WidgetSize.sm,
                        title: 'Nonthawit Doungsodsri Text',
                        color: AppColor.teal.c500,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(10000.00),
                      ),
                      AppAvatar(
                        style: WidgetStyle.subtle,
                        size: WidgetSize.md,
                        title: 'Nonthawit Doungsodsri Text',
                        color: AppColor.amber.c500,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(10000.00),
                      ),
                      AppAvatar(
                        style: WidgetStyle.subtle,
                        size: WidgetSize.lg,
                        title: 'Nonthawit Doungsodsri Text',
                        color: AppColor.green.c500,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(10000.00),
                      ),
                      AppAvatar(
                        style: WidgetStyle.subtle,
                        size: WidgetSize.xl,
                        title: 'Nonthawit Doungsodsri Text',
                        color: AppColor.red.c500,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(10000.00),
                      ),
                      AppAvatar(
                        style: WidgetStyle.subtle,
                        size: WidgetSize.xl,
                        title: 'Nonthawit Doungsodsri Text',
                        color: context.theme.color.bgInverse,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(10000.00),
                      ),
                      AppAvatar(
                        style: WidgetStyle.subtle,
                        size: WidgetSize.xxl,
                        title: 'Nonthawit Doungsodsri Text',
                        color: AppColor.violet.c500,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(10000.00),
                      ),
                      AppAvatar(
                        style: WidgetStyle.subtle,
                        size: WidgetSize.xxl,
                        title: 'Nonthawit Doungsodsri Text',
                        color: AppColor.violet.c500,
                        disabled: true,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(10000.00),
                      ),
                    ],
                  ),
                  WrapLayout(
                    gap: 20,
                    children: [
                      AppAvatar(
                        style: WidgetStyle.subtle,
                        size: WidgetSize.xs,
                        title: 'Nonthawit Doungsodsri Text',
                        color: AppColor.blue.c500,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(8.00),
                      ),
                      AppAvatar(
                        style: WidgetStyle.subtle,
                        size: WidgetSize.sm,
                        title: 'Nonthawit Doungsodsri Text',
                        color: AppColor.teal.c500,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(8.00),
                      ),
                      AppAvatar(
                        style: WidgetStyle.subtle,
                        size: WidgetSize.md,
                        title: 'Nonthawit Doungsodsri Text',
                        color: AppColor.amber.c500,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(8.00),
                      ),
                      AppAvatar(
                        style: WidgetStyle.subtle,
                        size: WidgetSize.lg,
                        title: 'Nonthawit Doungsodsri Text',
                        color: AppColor.green.c500,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(8.00),
                      ),
                      AppAvatar(
                        style: WidgetStyle.subtle,
                        size: WidgetSize.xl,
                        title: 'Nonthawit Doungsodsri Text',
                        color: AppColor.red.c500,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(8.00),
                      ),
                      AppAvatar(
                        style: WidgetStyle.subtle,
                        size: WidgetSize.xl,
                        title: 'Nonthawit Doungsodsri Text',
                        color: context.theme.color.bgInverse,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(8.00),
                      ),
                      AppAvatar(
                        style: WidgetStyle.subtle,
                        size: WidgetSize.xxl,
                        title: 'Nonthawit Doungsodsri Text',
                        color: AppColor.violet.c500,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(8.00),
                      ),
                      AppAvatar(
                        style: WidgetStyle.subtle,
                        size: WidgetSize.xxl,
                        title: 'Nonthawit Doungsodsri Text',
                        color: AppColor.violet.c500,
                        disabled: true,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(8.00),
                      ),
                    ],
                  ),
                ],
              ),
              SectionH2Widgetbook(
                title: 'Filled',
                children: [
                  WrapLayout(
                    gap: 20,
                    children: [
                      AppAvatar(
                        style: WidgetStyle.filled,
                        size: WidgetSize.xs,
                        title: 'Nonthawit Doungsodsri Text',
                        color: AppColor.blue.c500,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(10000.00),
                      ),
                      AppAvatar(
                        style: WidgetStyle.filled,
                        size: WidgetSize.sm,
                        title: 'Nonthawit Doungsodsri Text',
                        color: AppColor.teal.c500,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(10000.00),
                      ),
                      AppAvatar(
                        style: WidgetStyle.filled,
                        size: WidgetSize.md,
                        title: 'Nonthawit Doungsodsri Text',
                        color: AppColor.amber.c500,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(10000.00),
                      ),
                      AppAvatar(
                        style: WidgetStyle.filled,
                        size: WidgetSize.lg,
                        title: 'Nonthawit Doungsodsri Text',
                        color: AppColor.green.c500,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(10000.00),
                      ),
                      AppAvatar(
                        style: WidgetStyle.filled,
                        size: WidgetSize.xl,
                        title: 'Nonthawit Doungsodsri Text',
                        color: AppColor.red.c500,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(10000.00),
                      ),
                      AppAvatar(
                        style: WidgetStyle.filled,
                        size: WidgetSize.xl,
                        title: 'Nonthawit Doungsodsri Text',
                        color: context.theme.color.bgInverse,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(10000.00),
                      ),
                      AppAvatar(
                        style: WidgetStyle.filled,
                        size: WidgetSize.xxl,
                        title: 'Nonthawit Doungsodsri Text',
                        color: AppColor.violet.c500,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(10000.00),
                      ),
                      AppAvatar(
                        style: WidgetStyle.filled,
                        size: WidgetSize.xxl,
                        title: 'Nonthawit Doungsodsri Text',
                        color: AppColor.violet.c500,
                        disabled: true,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(10000.00),
                      ),
                    ],
                  ),
                  WrapLayout(
                    gap: 20,
                    children: [
                      AppAvatar(
                        style: WidgetStyle.filled,
                        size: WidgetSize.xs,
                        title: 'Nonthawit Doungsodsri Text',
                        color: AppColor.blue.c500,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(8.00),
                      ),
                      AppAvatar(
                        style: WidgetStyle.filled,
                        size: WidgetSize.sm,
                        title: 'Nonthawit Doungsodsri Text',
                        color: AppColor.teal.c500,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(8.00),
                      ),
                      AppAvatar(
                        style: WidgetStyle.filled,
                        size: WidgetSize.md,
                        title: 'Nonthawit Doungsodsri Text',
                        color: AppColor.amber.c500,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(8.00),
                      ),
                      AppAvatar(
                        style: WidgetStyle.filled,
                        size: WidgetSize.lg,
                        title: 'Nonthawit Doungsodsri Text',
                        color: AppColor.green.c500,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(8.00),
                      ),
                      AppAvatar(
                        style: WidgetStyle.filled,
                        size: WidgetSize.xl,
                        title: 'Nonthawit Doungsodsri Text',
                        color: AppColor.red.c500,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(8.00),
                      ),
                      AppAvatar(
                        style: WidgetStyle.filled,
                        size: WidgetSize.xl,
                        title: 'Nonthawit Doungsodsri Text',
                        color: context.theme.color.bgInverse,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(8.00),
                      ),
                      AppAvatar(
                        style: WidgetStyle.filled,
                        size: WidgetSize.xxl,
                        title: 'Nonthawit Doungsodsri Text',
                        color: AppColor.violet.c500,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(8.00),
                      ),
                      AppAvatar(
                        style: WidgetStyle.filled,
                        size: WidgetSize.xxl,
                        title: 'Nonthawit Doungsodsri Text',
                        color: AppColor.violet.c500,
                        disabled: true,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(8.00),
                      ),
                    ],
                  ),
                ],
              ),
              SectionH2Widgetbook(
                title: 'Image',
                children: [
                  WrapLayout(
                    gap: 20,
                    children: [
                      AppAvatar(
                        style: WidgetStyle.subtle,
                        size: WidgetSize.xs,
                        title: 'Nonthawit Doungsodsri Text',
                        path: Assets.mock.avatarSquared.keyName,
                        color: AppColor.blue.c500,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(10000.00),
                      ),
                      AppAvatar(
                        style: WidgetStyle.subtle,
                        size: WidgetSize.sm,
                        title: 'Nonthawit Doungsodsri Text',
                        path: Assets.mock.avatarSquared.keyName,
                        color: AppColor.teal.c500,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(10000.00),
                      ),
                      AppAvatar(
                        style: WidgetStyle.subtle,
                        size: WidgetSize.md,
                        title: 'Nonthawit Doungsodsri Text',
                        path: Assets.mock.avatarSquared.keyName,
                        color: AppColor.amber.c500,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(10000.00),
                      ),
                      AppAvatar(
                        style: WidgetStyle.subtle,
                        size: WidgetSize.lg,
                        title: 'Nonthawit Doungsodsri Text',
                        path: Assets.mock.avatarSquared.keyName,
                        color: AppColor.green.c500,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(10000.00),
                      ),
                      AppAvatar(
                        style: WidgetStyle.subtle,
                        size: WidgetSize.xl,
                        title: 'Nonthawit Doungsodsri Text',
                        path: Assets.mock.avatarSquared.keyName,
                        color: AppColor.red.c500,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(10000.00),
                      ),
                      AppAvatar(
                        style: WidgetStyle.subtle,
                        size: WidgetSize.xxl,
                        title: 'Nonthawit Doungsodsri Text',
                        path: Assets.mock.avatarSquared.keyName,
                        color: AppColor.violet.c500,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(10000.00),
                      ),
                      AppAvatar(
                        style: WidgetStyle.subtle,
                        size: WidgetSize.xxl,
                        title: 'Nonthawit Doungsodsri Text',
                        path: Assets.mock.avatarSquared.keyName,
                        color: AppColor.violet.c500,
                        disabled: true,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(10000.00),
                      ),
                    ],
                  ),
                  WrapLayout(
                    gap: 20,
                    children: [
                      AppAvatar(
                        style: WidgetStyle.subtle,
                        size: WidgetSize.xs,
                        title: 'Nonthawit Doungsodsri Text',
                        path: Assets.mock.avatarSquared.keyName,
                        color: AppColor.blue.c500,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(8.00),
                      ),
                      AppAvatar(
                        style: WidgetStyle.subtle,
                        size: WidgetSize.sm,
                        title: 'Nonthawit Doungsodsri Text',
                        path: Assets.mock.avatarSquared.keyName,
                        color: AppColor.teal.c500,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(8.00),
                      ),
                      AppAvatar(
                        style: WidgetStyle.subtle,
                        size: WidgetSize.md,
                        title: 'Nonthawit Doungsodsri Text',
                        path: Assets.mock.avatarSquared.keyName,
                        color: AppColor.amber.c500,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(8.00),
                      ),
                      AppAvatar(
                        style: WidgetStyle.subtle,
                        size: WidgetSize.lg,
                        path: Assets.mock.avatarSquared.keyName,
                        title: 'Nonthawit Doungsodsri Text',
                        color: AppColor.green.c500,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(8.00),
                      ),
                      AppAvatar(
                        style: WidgetStyle.subtle,
                        size: WidgetSize.xl,
                        title: 'Nonthawit Doungsodsri Text',
                        path: Assets.mock.avatarSquared.keyName,
                        color: AppColor.red.c500,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(8.00),
                      ),
                      AppAvatar(
                        style: WidgetStyle.subtle,
                        size: WidgetSize.xxl,
                        path: Assets.mock.avatarSquared.keyName,
                        title: 'Nonthawit Doungsodsri Text',
                        color: AppColor.violet.c500,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(8.00),
                      ),
                      AppAvatar(
                        style: WidgetStyle.subtle,
                        size: WidgetSize.xxl,
                        path: Assets.mock.avatarSquared.keyName,
                        title: 'Nonthawit Doungsodsri Text',
                        color: AppColor.violet.c500,
                        disabled: true,
                        border: Border.all(
                          width: 0.5,
                          color: AppLightThemeColor().border,
                          style: BorderStyle.solid,
                          strokeAlign: BorderSide.strokeAlignInside,
                        ),
                        borderRadius: BorderRadius.circular(8.00),
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        );
}
