name: core
description: A core project.
# Prevent accidental publishing to pub.dev.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  data:
    path: ../../packages/data
  design_system:
    path: ../../packages/design_system
  localization:
    path: ../../packages/localization
  utils:
    path: ../../packages/utils

  falconx:
    git:
      url: https://github.com/nextzy/falconx.git
      path: falconx
      ref: 3.6.0

  #======= Firebase ========#
  firebase_core: ^3.10.1
  firebase_remote_config: ^5.3.1

  #======= Utils ========#
  #PLATFORM: All
  flutter_dotenv: ^5.2.1
  upgrader: ^11.3.1
  freezed_annotation: ^2.4.4
  auto_route: ^9.3.0+1
  #PLATFORM: Android, iOS, MacOS, Webs, Windows
  wakelock_plus: ^1.2.10
  #PLATFORM: Android, iOS, MacOS, Windows
  screen_brightness: ^2.1.1
  #PLATFORM: Android, iOS, Windows
  permission_handler: ^11.3.1
  #PLATFORM: Android, iOS
  open_file: ^3.5.10
  flutter_upgrade_version: ^1.1.7


  #======= Analytic ========#
  #PLATFORM: All
  #catcher: ^1.0.0-dev1
  catcher:
    git:
      url: https://github.com/THE-EXISTING/catcher
      ref: master
  #PLATFORM: Android, iOS
  newrelic_mobile: ^1.1.7


dependency_overrides:

#  falconx:
#    path: ../../../FalconX/falconx


dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  auto_route_generator: ^9.0.0
  flutter_gen_runner: ^5.8.0
  json_serializable: ^6.9.0
  freezed: ^2.5.7


flutter:
  uses-material-design: true
  generate: true