name: utils
description: Function tools.
# Prevent accidental publishing to pub.dev.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  core:
    path: ../../packages/core


  #======= Utils ========#
  #PLATFORM: All
  http_parser: ^4.1.1
  intl: ^0.19.0
  encrypt: ^5.0.3
  url_launcher: ^6.3.1
  url_strategy: ^0.3.0
  timer_count_down: ^2.2.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  #PLATFORM: Android, iOS, Webs
  flutter_libphonenumber: ^2.5.0


dependency_overrides:
  # Fixed http_parser
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  flutter_lints: ^5.0.0

flutter_gen:
  output: lib/generated/

  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
      style: dot-delimiter

flutter:
  uses-material-design: true
  generate: true
